# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BOARD_NAME: native_posix
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          timeout-minutes: 2
          continue-on-error: true

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update

      - name: West build
        run: west build -p -b ${{ env.BOARD_NAME }} app

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: build
          path: build/zephyr/zephyr.elf


